name: Docker_Build
on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build For food boot
      uses: actions/checkout@v2
    
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository:  foot-boot/food-delivery-web-app-backend-springboot food-delivery-api/food-delivery-api:docker
        tag_with_ref: true

